# Note that for this workflow to be triggered, the tag needs to be
# created of the form `libs/uuid/<version>+<buildinfo>`, where <buildinfo>
# by convention is YYYYMMDD-<short-sha> (short SHA can be calculated
# with `git rev-parse --short HEAD`). An example of a tag following
# the convention that triggers automation would be
# `libs/uuid/1.0.3+20230131-8dfe8b9`.
name: Release LibUuid
on:
  push:
    tags:
      - libs/uuid/*
jobs:
  release-uuid:
    strategy:
      matrix:
        include:
          - version: 1.0.3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Only run for the LibUuid version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: startsWith(github.event.ref,  format('refs/tags/libs/uuid/{0}+', matrix.version))
        uses: actions/checkout@v3
      - name: Build LibUuid
        # Only run for the LibUuid version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: startsWith(github.event.ref, format('refs/tags/libs/uuid/{0}+', matrix.version))
        run: make libs/uuid/libuuid-${{ matrix.version }}
      - name: Bundle LibUuid with standard libraries
        # Only run for the LibUuid version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: startsWith(github.event.ref, format('refs/tags/libs/uuid/{0}+', matrix.version))
        run: |
          pushd libs/uuid/build-output/uuid/libuuid-${{ matrix.version }}
          sudo zip -qq -r libuuid-${{ matrix.version }}.zip include lib
          popd
      - name: Create release
        # Only run for the LibUuid version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: startsWith(github.event.ref, format('refs/tags/libs/uuid/{0}+', matrix.version))
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --generate-notes ${{ github.ref_name }} || true
      - name: Append LibUuid release assets
        # Only run for the LibUuid version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: ${{ startsWith(github.event.ref, format('refs/tags/libs/uuid/{0}+', matrix.version))}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} \
            libs/uuid/build-output/uuid/libuuid-${{ matrix.version }}/libuuid-${{ matrix.version }}.zip
      - name: Generate release assets digests
        # Only run for the LibUuid version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: ${{ startsWith(github.event.ref, format('refs/tags/libs/uuid/{0}+', matrix.version))}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for asset in libs/uuid/build-output/uuid/libuuid-${{ matrix.version }}/libuuid-${{ matrix.version }}.zip; do
            sha256sum "$asset" | sudo tee "$asset.sha256sum" > /dev/null
          done
      - name: Append release assets digests
        # Only run for the LibUuid version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: ${{ startsWith(github.event.ref, format('refs/tags/libs/uuid/{0}+', matrix.version))}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} \
            libs/uuid/build-output/uuid/libuuid-${{ matrix.version }}/libuuid-${{ matrix.version }}.zip.sha256sum

