# Note that for this workflow to be triggered, the tag needs to be
# created of the form `libs/uuid/<version>+<buildinfo>`, where <buildinfo>
# by convention is YYYYMMDD-<short-sha> (short SHA can be calculated
# with `git rev-parse --short HEAD`). An example of a tag following
# the convention that triggers automation would be
# `libs/uuid/1.0.3+20230131-8dfe8b9`.
name: Release LibUuid
on:
  push:
    tags:
      - libs/uuid/*
jobs:
  release-uuid:
    uses: ./.github/workflows/reusable-release-lib.yaml
    with:
      name: "libuuid"
      target-name: "uuid"
      target-prefix: "libuuid-"
      trigger: ${{ github.event.ref }}
